/*
Automatically generated code. DO NOT edit this file!

To use, ensure the following:

1. That this code is copied into the application that is going to communicate with the server.
2. That server-bridge-superagent-client is added as a dependency in the client application. Install it by running:

   npm install --save server-bridge-superagent-client
*/
import {ClientBase} from "server-bridge-superagent-client";

export interface Note {
    text: string;
    creationDate: Date;
}

export class NoteApi extends ClientBase {
    constructor(options?: { urlPrefix: string; }) {
        super((options == null ? "" : (options.urlPrefix || "")) + "");
    }

    getAll() {
        return super.get<Note[]>("/getAll");
    }

    getAllWithText(params: { text: string; }) {
        return super.get<Note[]>("/", params);
    }

    add(note: Note) {
        return super.post<void>("/", note);
    }
}
