"use strict";
/*
Automatically generated code. DO NOT edit this file!

To use, ensure the following:

1. That this code is copied into the application that is going to communicate with the server.
2. That server-bridge-superagent-client is added as a dependency in the client application. Install it by running:

   npm install --save server-bridge-superagent-client
*/
const server_bridge_superagent_client_1 = require("server-bridge-superagent-client");
class NoteApi extends server_bridge_superagent_client_1.ClientBase {
    constructor(options) {
        super((options == null ? "" : (options.urlPrefix || "")) + "");
    }
    getAll() {
        return super.get("/getAll");
    }
    getAllWithText(params) {
        return super.get("/", params);
    }
    add(note) {
        return super.post("/", note);
    }
}
exports.NoteApi = NoteApi;
//# sourceMappingURL=server.js.map